{
 "title": "Version overview",
 "tags": [
  "version-exporter",
  "k8s"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=~\"$cluster\"}, exported_namespace) "
    }
   },
   {
    "name": "version_metrics",
    "query": {
     "query": "query_result({cluster=~\"$cluster\",dashboard=\"qubership-version-exporter\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "kubernetes",
   "type": "table",
   "description": "Shows kubernetes build and node info",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kubernetes_build_info{cluster=~\"$cluster\"}"
    },
    {
     "expr": "kube_node_info{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "etcd ",
   "type": "table",
   "description": "Shows server version info",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "etcd_server_version{cluster=~\"$cluster\"}"
    },
    {
     "expr": "etcd_cluster_version{cluster=~\"$cluster\"}"
    },
    {
     "expr": "etcd_server_go_version{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "coredns",
   "type": "table",
   "description": "Shows build info. In kubernetes only.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "coredns_build_info{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "nginx ingress",
   "type": "table",
   "description": "Shows build info. In kubernetes only.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "nginx_ingress_controller_build_info{cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Monitoring services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Grafana",
     "type": "stat",
     "description": "Shows build info.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group(grafana_build_info{cluster=~\"$cluster\"}) by (namespace)",
       "legendFormat": "namespace - {{namespace}}"
      },
      {
       "expr": "group(grafana_build_info{cluster=~\"$cluster\"}) by (version)",
       "legendFormat": "version - {{version}}"
      },
      {
       "expr": "group(grafana_build_info{cluster=~\"$cluster\"}) by (goversion)",
       "legendFormat": "goversion - {{goversion}}"
      }
     ]
    },
    {
     "title": "Prometheus",
     "type": "stat",
     "description": "Shows build info.",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group(prometheus_build_info{cluster=~\"$cluster\"}) by (namespace)",
       "legendFormat": "namespace - {{namespace}}"
      },
      {
       "expr": "group(prometheus_build_info{cluster=~\"$cluster\"}) by (version)",
       "legendFormat": "version - {{version}}"
      },
      {
       "expr": "group(prometheus_build_info{cluster=~\"$cluster\"}) by (goversion)",
       "legendFormat": "goversion - {{goversion}}"
      }
     ]
    },
    {
     "title": "Prometheus Operator",
     "type": "stat",
     "description": "Shows build info.",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group(prometheus_operator_build_info{cluster=~\"$cluster\"}) by (namespace)",
       "legendFormat": "namespace - {{namespace}}"
      },
      {
       "expr": "group(prometheus_operator_build_info{cluster=~\"$cluster\"}) by (version)",
       "legendFormat": "version - {{version}}"
      },
      {
       "expr": "group(prometheus_operator_build_info{cluster=~\"$cluster\"}) by (goversion)",
       "legendFormat": "goversion - {{goversion}}"
      }
     ]
    },
    {
     "title": "Alert Manager",
     "type": "stat",
     "description": "Shows build info.",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group(alertmanager_build_info{cluster=~\"$cluster\"}) by (namespace)",
       "legendFormat": "namespace - {{namespace}}"
      },
      {
       "expr": "group(alertmanager_build_info{cluster=~\"$cluster\"}) by (version)",
       "legendFormat": "version - {{version}}"
      },
      {
       "expr": "group(alertmanager_build_info{cluster=~\"$cluster\"}) by (goversion)",
       "legendFormat": "goversion - {{goversion}}"
      }
     ]
    },
    {
     "title": "Node Exporter",
     "type": "stat",
     "description": "Shows build info.",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group(node_exporter_build_info{cluster=~\"$cluster\"}) by (namespace)",
       "legendFormat": "namespace - {{namespace}}"
      },
      {
       "expr": "group(node_exporter_build_info{cluster=~\"$cluster\"}) by (version)",
       "legendFormat": "version - {{version}}"
      },
      {
       "expr": "group(node_exporter_build_info{cluster=~\"$cluster\"}) by (goversion)",
       "legendFormat": "goversion - {{goversion}}"
      }
     ]
    },
    {
     "title": "Version Exporter",
     "type": "stat",
     "description": "Shows build info.",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "group(version_exporter_build_info{cluster=~\"$cluster\"}) by (namespace)",
       "legendFormat": "namespace  - {{namespace}}"
      },
      {
       "expr": "group(version_exporter_build_info{cluster=~\"$cluster\"}) by (version)",
       "legendFormat": "version - {{version}}"
      },
      {
       "expr": "group(version_exporter_build_info{cluster=~\"$cluster\"}) by (goversion)",
       "legendFormat": "goversion - {{goversion}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Image",
     "type": "table",
     "description": "Shows pod container info.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "kube_pod_container_info{cluster=~\"$cluster\",exported_namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Init Container",
     "type": "table",
     "description": "Shows build pod init container info.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "kube_pod_init_container_info{cluster=~\"$cluster\",exported_namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Golang",
     "type": "table",
     "description": "Shows go info.",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "go_info{cluster=~\"$cluster\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Python",
     "type": "table",
     "description": "Shows python info.",
     "gridPos": { "h": 5, "w": 13, "x": 11, "y": 24 },
     "targets": [
      {
       "expr": "python_info{cluster=~\"$cluster\",namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "JVM",
     "type": "table",
     "description": "Shows jvm info.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "jvm_info{cluster=~\"$cluster\",namespace=\"$namespace\"}"
      }
     ]
    }
   ]
  },
  { "title": "Version exporter metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "The information collected here is aggregated by \"dashboard=\"qubership-version-exporter\"\" label."
   }
  },
  {
   "title": "$version_metrics",
   "type": "table",
   "description": "Shows collected $version_metrics metric info.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "repeat": "version_metrics",
   "targets": [
    {
     "expr": "{__name__=\"$version_metrics\", cluster=~\"$cluster\"}"
    }
   ]
  }
 ]
}