name: Go test with Sonar
on:
  push: {}
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  pull-requests: write
  packages: write
jobs:
  test:
    name: Build and test with coverage
    uses: Netcracker/qubership-core-infra/.github/workflows/generic-go-build.yaml@bc2a0bd082147e23b4091616c608a21cc2957728 # v2.4.1
    with:
      go-module-dir: '.'
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
      cover-packages: './pkg/...'
      skip-docker: true
    secrets: inherit
