name: Go test
on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]
permissions:
  contents: read
jobs:
  test:
    uses: netcracker/qubership-core-infra/.github/workflows/go-build-with-sonar.yaml@c36c6cf6875af12c5708dcdbe088a887be55785c # v2.2.0
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
