name: Go test
on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]
permissions:
  contents: read
jobs:
  test:
    uses: netcracker/qubership-core-infra/.github/workflows/go-build-with-sonar.yaml@b9ddd544e3b5b17a31866d34c220b14e76681f31 # v2.3.0
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
